using System.Collections.Generic;

namespace TreParking_wpf.Model
{
    /// <summary>
    /// Main parking data object. File was generated by json2csharp.com from the API result so names are a bit off and strange.
    /// </summary>
    public class ParkingData
    {
        public class SupplierIdentification
        {
            public string country { get; set; }
            public string nationalIdentifier { get; set; }
        }

        public class Exchange
        {
            public SupplierIdentification supplierIdentification { get; set; }
        }

        public class PublicationCreator
        {
            public string country { get; set; }
            public string nationalIdentifier { get; set; }
        }

        public class HeaderInformation
        {
            public string areaOfInterest { get; set; }
            public string confidentiality { get; set; }
            public string informationStatus { get; set; }
        }

        public class CarParkDetails
        {
            public string tag { get; set; }
            public string value { get; set; }
        }

        public class PointCoordinates
        {
            public string latitude { get; set; }
            public string longitude { get; set; }
        }

        public class PointByCoordinates
        {
            public PointCoordinates pointCoordinates { get; set; }
        }

        public class EntranceLocation
        {
            public PointByCoordinates pointByCoordinates { get; set; }
        }

        public class ParkingFacility
        {
            public string id { get; set; }
            public string version { get; set; }
            public string parkingFacilityName { get; set; }
            public string parkingFacilityRecordVersionTime { get; set; }
            public CarParkDetails carParkDetails { get; set; }
            public EntranceLocation entranceLocation { get; set; }
        }

        public class ParkingFacilityTable
        {
            public string parkingFacilityTableName { get; set; }
            public string parkingFacilityTableVersionTime { get; set; }
            public List<ParkingFacility> parkingFacility { get; set; }
        }

        public class ParkingFacilityTablePublication
        {
            public HeaderInformation headerInformation { get; set; }
            public ParkingFacilityTable parkingFacilityTable { get; set; }
        }

        public class HeaderInformation2
        {
            public string areaOfInterest { get; set; }
            public string confidentiality { get; set; }
            public string informationStatus { get; set; }
        }

        public class ParkingFacilityReference
        {
            public string id { get; set; }
            public string version { get; set; }
            public string targetClass { get; set; }
        }

        public class ParkingFacilityStatu
        {
            public ParkingFacilityReference parkingFacilityReference { get; set; }
            public object parkingFacilityStatus { get; set; }
            public string parkingFacilityStatusTime { get; set; }
            public string parkingFacilityOccupancyTrend { get; set; }
        }

        public class ParkingFacilityTableStatusPublication
        {
            public HeaderInformation2 headerInformation { get; set; }
            public List<ParkingFacilityStatu> parkingFacilityStatus { get; set; }
        }

        public class GenericPublicationExtension
        {
            public ParkingFacilityTablePublication parkingFacilityTablePublication { get; set; }
            public ParkingFacilityTableStatusPublication parkingFacilityTableStatusPublication { get; set; }
        }

        public class PayloadPublication
        {
            public string publicationTime { get; set; }
            public PublicationCreator publicationCreator { get; set; }
            public string genericPublicationName { get; set; }
            public GenericPublicationExtension genericPublicationExtension { get; set; }
        }

        public class D2LogicaModel
        {
            public Exchange exchange { get; set; }
            public PayloadPublication payloadPublication { get; set; }
        }

        public class RootObject
        {
            public D2LogicaModel d2LogicaModel { get; set; }
        }
    }
}